/* explain.js — mapa de termos -> explicacao didatica.
   O servidor anexa `explain` a cada modulo casando estes termos nos topicos de `start`.
   Assim TODAS as trilhas ganham explicacao do que é cada coisa, sem duplicar 1521 textos. */
const MAP = {
  // ---------- matematica basica / pre-calculo ----------
  "conjuntos": "Conjuntos são coleções de elementos definidos por uma propriedade comum. São a base da lógica, da probabilidade e de quase toda a matemática formal.",
  "reais": "Os números reais incluem racionais (frações) e irracionais (π, √2). É o conjunto que usamos para medir quantidades contínuas no mundo real.",
  "complexos": "Números complexos somam uma unidade imaginária i (onde i² = -1) aos reais. Essenciais em engenharia, sinais e equações sem raiz real.",
  "intervalos": "Intervalos descrevem faixas contínuas de números (ex.: [0,1]). São a forma de falar de domínios e conjuntos infinitos sem listar tudo.",
  "valor absoluto": "Valor absoluto |x| é a distância de x até zero, sempre positiva. Mede tamanho, não direção — chave em desigualdades e erros.",
  "desigualdades": "Desigualdades comparam grandezas com <, >, ≤, ≥. Resolvê-las é achar os intervalos onde a afirmação vale.",
  "notação": "Notação matemática é a linguagem compacta (símbolos, conjuntos, funções). Dominá-la é ler e escrever matemática sem ambiguidade.",
  "função": "Uma função associa cada entrada a exatamente uma saída: f(x). É a ideia central de modelar relações e de programação.",
  "domínio": "Domínio é o conjunto de entradas válidas de uma função; contradomínio é onde a saída vive. Fora do domínio a função não existe.",
  "gráfico": "O gráfico é a imagem da função no plano. Visualizar curvas revela crescimento, raízes e comportamento que números escondem.",
  "zero da função": "Zero da função é onde f(x)=0 (a curva cruza o eixo x). São as soluções da equação e pontos-chave de análise.",
  "crescimento": "Crescimento diz se a função sobe ou desce. O sinal da derivada (depois) classifica isso com precisão.",
  "simetria": "Simetria (par/ímpar) poupa trabalho: função par espelha no eixo y, ímpar no centro. Reconhecê-la simplifica contas e gráficos.",
  "fatoração": "Fatorar é escrever uma expressão como produto de fatores. Abre portas para resolver equações e simplificar frações.",
  "produtos notáveis": "São padrões de multiplicação prontos (quadrado da soma, diferença de quadrados). Decorá-los acelera álgebra inteira.",
  "divisão": "Divisão de polinômios repete o esquema de dividir, multiplicar e subtrair. Base para o Teorema do Resto.",
  "teorema resto": "O Teorema do Resto diz que o resto de f(x) por (x-a) é f(a). Liga avaliação de função a divisão — atalho poderoso.",
  "equações": "Equações pedem o valor que torna a igualdade verdadeira. Resolvê-las é o dia a dia da álgebra aplicada.",
  "sistemas": "Sistemas são várias equações juntas; a solução satisfaz todas. Modelam problemas com várias incógnitas de verdade.",
  "antiderivada": "Antiderivada é a função cuja derivada é a dada. É o inverso da derivada e a porta de entrada para a integral.",
  "+C": "A constante +C aparece na antiderivada porque derivar uma constante dá zero: infinitas primitivas deslocadas.",
  "potência": "A regra da potência integra x^n como x^(n+1)/(n+1). É a operação mais usada em cálculo integral.",
  "soma": "A integral é linear: a integral da soma é a soma das integrais. Permite quebrar problemas grandes em pedaços.",
  "expo/log": "Exponenciais e logaritmos são inversos. Integrá-los aparece em crescimento, decaimento e escala natural.",
  "verificar": "Verificar uma integral derivando o resultado confirma se acertou. É o teste grátis que toda conta merece.",
  "soma de riemann": "Soma de Riemann aproxima área por retângulos sob a curva. O limite dessa soma É a integral definida.",
  "tfc": "O Teorema Fundamental do Cálculo liga derivada e integral: integrar é 'desfazer' derivar. A ponte mais importante do cálculo.",
  "limite": "Limite descreve para onde a função tende, mesmo sem chegar. Base para continuidade, derivada e integral.",
  "área": "A integral definida calcula área com sinal entre curva e eixo x. Negativo embaixo vira área 'perdida'.",
  "sinal": "O sinal da função diz onde ela está acima/abaixo do eixo. Define se a área conta positiva ou negativa.",
  "geometria": "Interpretar integral geometricamente (área, volume) dá intuição física, não só conta simbólica.",
  "substituição": "Substituição (mudança de variável) simplifica integrais como o chain rule invertido. A técnica mais usada.",
  "por partes": "Integração por partes vem do produto da derivada: ∫u dv = uv − ∫v du. Para produtos de funções.",
  "frações parciais": "Frações parciais decompõem racionais em pedaços simples de integrar. Chave para álgebra integral.",
  "trig": "Integrais trigonométricas usam identidades (sen²+cos²=1) para simplificar. Aparecem em ondas e rotação.",
  "escolha": "Escolher a técnica certa (substituição, partes, parciais) vem com prática — reconhecer o 'cheiro' do integrando.",
  "estratégia": "Estratégia de integração: tente substituição, depois partes, depois parciais. Ordem importa para não sofrer.",
  "derivada": "Derivada é a taxa de variação instantânea — a inclinação da reta tangente. Mede como algo muda no momento exato.",
  "cadeia": "A regra da cadeia deriva funções compostas: (f∘g)' = f'(g)·g'. Onipresente porque tudo é composto.",
  "tangente": "A reta tangente toca a curva num ponto com a mesma inclinação. Visualiza a derivada como 'direção local'.",
  "polinômio": "Polinômios são somas de potências; fáceis de derivar/integrar termo a termo. Base de aproximações.",
  "raízes": "Raízes são onde a função zera. Classificar máximos/mínimos depende do sinal da derivada em volta delas.",
  "taylor": "Séries de Taylor aproximam funções por polinômios usando derivadas sucessivas. Liga cálculo a computação.",
  "maclaurin": "Maclaurin é Taylor centrada em zero. Ex.: e^x, seno e cosseno viram polinômios infinitos.",
  "weierstrass": "Weierstrass deu um exemplo de função contínua em lugar nenhum diferenciável — mostra que intuição pode falhar.",
  "mvt": "O Teorema do Valor Médio garante um ponto onde a derivada igual a inclinação média. Base de desigualdades e provas.",
  "teorema valor médio": "O Valor Médio liga derivada (local) a diferença (global). Se a velocidade média foi X, em algum momento foi X.",
  "teorema valor intermédio": "Se a função é contínua, ela assume todos os valores entre f(a) e f(b). Por isso raízes existem em intervalos.",
  "infinito": "Infinito em cálculo é limite, não número mágico. Séries e integrais improérias tratam 'até o infinito' com cuidado.",
  "séries": "Séries somam termos em sequência. Convergir (chegar a um valor) ou divergir decide se a soma faz sentido.",
  "p-série": "p-séries Σ1/n^p convergem se p>1. Referência rápida para comparar outras séries.",
  "teste": "Testes de convergência (comparação, razão, integral) dizem se uma série estabiliza ou explode.",
  "mínimos quadrados": "Mínimos quadrados ajusta uma reta minimizando erros ao quadrado. Base da regressão e do machine learning.",
  "r²": "R² mede quanto do comportamento os dados explicam pelo modelo. Próximo de 1 = bom ajuste.",
  "matriz": "Matrizes são tabelas de números que representam transformações lineares. O coração da álgebra linear.",
  "vetor": "Vetores têm módulo e direção; representam forças, deslocamentos e dados. Soma e produto interno medem relações.",
  "autovalor": "Autovalores/autovetores dizem como uma transformação age em direções que só escalam. Chave em PCA e dinâmica.",
  "transposta": "Transpor troca linhas por colunas. Útil em álgebra linear, estatística e multiplicação de matrizes.",
  "determinante": "O determinante diz se uma matriz é invertível e 'quanto' ela escala área/volume. Zero = transformação esmaga.",
  "espaço vetorial": "Espaço vetorial é um conjunto onde somar e multiplicar por escalar faz sentido. Moldura da álgebra linear.",
  "norma": "Norma mede o 'tamanho' de um vetor (ex.: comprimento). Generaliza distância para muitas dimensões.",

  // ---------- física / sinais ----------
  "lei ohm": "Lei de Ohm (V = R·I) liga tensão, resistência e corrente. Base de circuitos elétricos.",
  "tensão": "Tensão é a diferença de potencial que empurra a corrente. Como 'pressão' elétrica.",
  "corrente": "Corrente é a taxa de fluxo de carga. Medida em amperes; é o que realmente faz acontecer.",
  "resistores": "Resistores limitam corrente e dissipam energia em calor. Série somam; paralelo dividem.",
  "capacitores": "Capacitores armazenam carga em campo elétrico. Reagem rápido a mudanças de tensão.",
  "circuitos": "Circuitos combinam componentes segundo leis de Kirchhoff. Modelam o hardware real.",
  "senóide": "Senoide é a onda pura sen/cos. Tudo em sinais periódicos se decompõe nela (Fourier).",
  "fourier": "Fourier decompõe qualquer sinal periódico em senoides. Base de áudio, imagem e comunicação.",
  "frequência": "Frequência é quantas oscilações por segundo (Hz). Determina tom, cor e canal de rádio.",
  "amplitude": "Amplitude é o pico do sinal. Relaciona-se à energia/intensidade (som alto, luz forte).",
  "wavelength": "Comprimento de onda é a distância entre picos. Inversamente proporcional à frequência.",
  "velocidade": "Velocidade é derivada da posição no tempo. Fisicamente, é a taxa de variação do movimento.",
  "aceleração": "Aceleração é a derivada da velocidade. Segunda derivada da posição — 'quão rápido a velocidade muda'.",
  "energia": "Energia é a capacidade de realizar trabalho. Integrar potência no tempo a mede.",
  "trabalho": "Trabalho é força aplicada ao longo de um deslocamento. Área sob a curva força×distância.",
  "conservação": "Leis de conservação (energia, momento) dizem o que não muda num sistema fechado. Ponto de partida de física.",
  "newton": "As leis de Newton relacionam força, massa e aceleração (F = m·a). Base da mecânica clássica.",
  "newton 2ª lei": "A 2ª lei de Newton (F = m·a) diz que força produz aceleração proporcional à massa.",
  "quantização": "Quantização é variável em pacotes discretos (ex.: carga, energia). O salto entre clássico e quântico.",

  // ---------- programacao / python ----------
  "repl": "REPL é o loop 'leia-avalie-imprima' interativo do Python. Laboratório ideal para testar ideias na hora.",
  "variáveis": "Variáveis nomeiam valores na memória. Entender tipos (int, str, list) evita 90% dos erros iniciais.",
  "list/dict/set/tuple": "São as 4 estruturas centrais: lista ordenada, dicionário chave-valor, conjunto sem repetição, tupla imutável.",
  "laços": "Laços (for/while) repetem blocos. if/elif ramificam a lógica. O controle de fluxo é o esqueleto de todo programa.",
  "compreensões de lista": "Compreensões criam listas numa linha: [x for x in l if cond]. Concisas e rápidas em Python.",
  "def": "def cria funções — blocos reutilizáveis que recebem entrada e devolvem saída. Modulariza o código.",
  "*args e **kwargs": "Coletam argumentos variáveis: *args como tupla, **kwargs como dicionário. Flexibiliza assinaturas.",
  "escopo legb": "Escopo LEGB: Local, Enclosing, Global, Built-in. A ordem que o Python usa para achar uma variável.",
  "recursão": "Recursão é função que chama a si mesma. Elegante para problemas dividíveis (árvore, fatorial).",
  "type hints": "Type hints documentam tipos (def f(x: int) -> str). mypy os verifica sem mudar o runtime.",
  "pyproject": "pyproject.toml é o arquivo moderno de configuração de pacote Python (dependências, build, ferramentas).",
  "__init__": "__init__.py e imports organizam pacotes; __init__ inicializa módulos. Estrutura que todo projeto grande precisa.",
  "venv": "venv cria ambiente isolado de bibliotecas. Evita conflito de versões entre projetos.",
  "oop": "OOP modela o mundo em objetos (classes). Herança reaproveita; encapsulamento esconde detalhes.",
  "herança": "Herança faz uma classe estender outra (super()). Reuso sem copiar código.",
  "@property": "@property expõe método como atributo; setter valida ao atribuir. Encapsulamento limpo.",
  "dataclasses": "dataclasses geram automaticamente __init__/__repr__ para classes de dados. Menos código repetido.",
  "async": "asyncio permite concorrência com corrotinas (async/await) sem threads. Ideal para I/O (rede, arquivos).",
  "gather": "asyncio.gather roda várias corrotinas ao mesmo tempo e espera todas. Paraleliza I/O eficientemente.",
  "gil": "O GIL limita Python a 1 thread de CPU por processo. Para CPU pesada use multiprocessing, não threads.",
  "pillars": "Pacotes (pip install) trazem bibliotecas prontas. Saber buscar e versionar dependências é essencial.",
  "pytest": "pytest roda testes automaticamente. Testes pegam regressões antes do usuário ver o bug.",
  "cli": "CLI (linha de comando) torna scripts reutilizáveis por humanos e outros programas. typer facilita criar.",
  "requests": "A biblioteca requests faz chamadas HTTP simples. Base para consumir APIs.",
  "aiohttp": "aiohttp faz HTTP assíncrono, combinando com asyncio para muitas requisições simultâneas.",

  // ---------- git / eng / devops ----------
  "rebase/--amend": "rebase reorganiza commits; --amend corrige o último. Ferramentas de histórico limpo e linear.",
  "commits atômicos": "Commits atômicos agrupam UMA mudança lógica. Facilita revisar, reverter e entender a história.",
  "conventional commits": "Conventional Commits padroniza mensagens (feat:, fix:). Habilita changelogs e versionamento automático.",
  "branches feature": "Branches de feature isolam trabalho de cada pessoa/tarefa. Permite paralelismo sem conflito.",
  "code review": "Revisão de código é outro dev olhar suas mudanças. Pega bugs e espalha conhecimento antes do merge.",
  "conflitos": "Conflitos surgem quando duas mudanças batem na mesma linha. Resolver é escolher/integrar manualmente.",
  "solid": "SOLID são 5 princípios de design (responsabilidade única, aberto-fechado, etc). Código manutenível.",
  "repository/factory": "Repository isola acesso a dados; Factory cria objetos sem acoplar a classe concreta. Padrões de desacoplamento.",
  "adas": "Camadas (ex.: controller/service/repository) separam responsabilidades. Cada uma muda por um motivo.",
  "adr": "ADR (Architecture Decision Record) documenta decisões arquiteturais e o porquê. Memória do projeto.",
  "acoplamento": "Acoplamento é o quanto módulos dependem uns dos outros. Menos acoplamento = mais fácil de mudar.",
  "pirâmide": "A pirâmide de testes (muitos unit, poucos E2E) equilibra velocidade e confiança. Base do teste eficiente.",
  "cobertura": "Cobertura mede que fração do código os testes exercitam. Útil, mas 100% não garante correção.",
  "profiling": "Profiling aponta onde o tempo/CPU realmente vai. Otimiza-se o gargalo, não o chute.",
  "e2e": "Testes end-to-end exercitam o sistema inteiro como o usuário. Lentos, mas pegam integração quebrada.",
  "mocks": "Mocks substituem dependências reais (BD, API) em teste. Isolam a unidade sob teste.",
  "tdd": "TDD escreve o teste antes do código. Força clarificar o contrato e evita testar demais o óbvio.",
  "ci": "CI (Integração Contínua) roda build+testes a cada commit. Pega erros cedo, automaticamente.",
  "dockerfile": "Dockerfile multi-stage builda em etapas e descarta o desnecessário — imagem final enxuta e segura.",
  "vm/cts": "VMs são máquinas completas; CTs (containers) compartilham o kernel. Containers são leves e rápidos.",
  "thin pools": "Thin pools alocam disco sob demanda, não tudo de uma vez. Otimiza armazenamento de muitas VMs.",
  "snapshots": "Snapshots congelam o estado da VM num instante. Rollback é voltar a ele — protege contra erro.",
  "compose": "Docker Compose define vários containers (app+banco) num arquivo. Sobe o ambiente inteiro com 1 comando.",
  "elasticsearch+kibana": "Elasticsearch indexa logs; Kibana visualiza. Dupla clássica de observabilidade e busca.",
  "grafana": "Grafana monta dashboards de métricas (Prometheus, Loki). O que os on-call olham.",
  "prometheus": "Prometheus coleta métricas por pull em intervalos. Padrão de monitoramento cloud-native.",
  "loki": "Loki armazena logs como Prometheus armazena métricas — barato e integrável ao Grafana.",
  "otel": "OpenTelemetry padroniza traces/metrics/logs. Instrumenta uma vez, exporta para onde quiser.",
  "alerting": "Alerting dispara aviso quando algo quebra. Bons alertas têm limiar e dono — ruins geram fadiga.",
  "runbook": "Runbook é o passo a passo de como responder a um incidente. Quem acorda de madrugada precisa dele.",
  "postmortem": "Postmortem documenta o que aconteceu sem culpar pessoas. Foco em melhorar o sistema.",
  "mtld": "MTTD/MTTR medem tempo até detectar e até resolver. A saúde da operação.",
  "sla/slo/sli": "SLI é a métrica observada; SLO é a meta; SLA é o compromisso contratual. Base de confiabilidade.",
  "ansible": "Ansible automatiza configuração por SSH, sem agente. IaC declarativo e legível.",
  "terraform": "Terraform cria infra como código (nuvens, redes). Mudanças revisáveis em git, não cliques manuais.",
  "container": "Containers empacotam app+dependências. Rodam igual em dev, stage e produção.",

  // ---------- seguranca ----------
  "owasp top 10": "OWASP Top 10 lista as 10 vulnerabilidades web mais críticas. Checklist obrigatório de quem faz app.",
  "sql": "SQL injeta comandos no banco se a entrada não for tratada. Use prepared statements — nunca concatenar.",
  "xss": "XSS injeta script no navegador da vítima. Escape a saída e defina CSP para mitigar.",
  "sqli/xss": "SQLi e XSS são as injeções clássicas de web. Validação de entrada + escape de saída as evitam.",
  "mitre": "MITRE ATT&CK é o catálogo de táticas e técnicas de adversários. Linguagem comum de defesa e caça.",
  "cvss": "CVSS pontua a severidade de vulnerabilidades (0-10). Base para priorizar o que consertar primeiro.",
  "cve": "CVE é o identificador público de uma vulnerabilidade conhecida. Como se 'nomeia' um bug de segurança.",
  "ids/ips": "IDS detecta intrusão; IPS bloqueia. Sensores na rede que comparam tráfego a assinaturas/comportamento.",
  "suricata": "Suricata é um IDS/IPS aberto de alta performance. Inspeciona tráfego e gera alertas.",
  "edr": "EDR (Endpoint Detection and Response) monitora estações: detecta, investiga e responde a ameaças no host.",
  "hunting": "Caça de ameaças parte de hipóteses ('alguém moveu dados?') e busca evidências ativamente no ambiente.",
  "ir": "Resposta a incidentes (IR) contém, erradica e recupera. Conter limita o dano; erradicar remove a causa.",
  "phishing": "Phishing engana a vítima a entregar credenciais. Funciona por engenharia social, não só técnica.",
  "kerberos": "Kerberos é o protocolo de autenticação do AD. Kerberoasting abusa de tickets para quebrar senhas fracas.",
  "ad": "Active Directory é o diretório/identidade da Microsoft. Privesc de AD é escalar privilégio no domínio.",
  "bloodhound": "BloodHound mapeia relações de acesso no AD. Defensores acham caminhos de ataque; atacantes também.",
  "privesc": "Privilege escalation ganha mais acesso do que se deveria. Local (na máquina) ou domínio (AD).",
  "lateral": "Movimento lateral é o atacante saltar entre hosts usando credenciais roubadas. Segmentação dificulta.",
  "pivoting": "Pivoting usa um host comprometido como ponte para redes que ele alcança mas você não. SSH/chisel.",
  "c2": "Command & Control é o canal pelo qual o atacante comanda o malware. Detectar C2 = pegar o ataque.",
  "opsec": "OPSEC protege informação sensível que revela intenções. O que você posta pode ajudar o adversário.",
  "evasão de logs": "Evasão de logs apaga ou falsifica registros para esconder a presença. Boa auditoria dificulta.",
  "timestomping": "Timestomping altera timestamps de arquivos para confundir a linha do tempo forense. Parte da anti-análise.",
  "forense": "Forense digital preserva e analisa evidências de forma científica. Cadeia de custódia é sagrada.",
  "yara": "YARA cria regras para identificar malware por padrões de bytes/strings. Como um 'antivírus sob medida'.",
  "volatility": "Volatility 3 analisa memory dumps (RAM). Revela processos, conexões e malware que não está no disco.",
  "imagem de disco": "Imagem de disco é a cópia bit-a-bit do armazenamento. Feita antes de tocar em qualquer coisa.",
  "lei 12.737/12": "Lei 12.737/12 (Lei Carolina Dieckmann) criminaliza invasão de dispositivo. Estudo de segurança exige autorização.",
  "hammer": "Sandbox isolada executa malware em ambiente trancado para observar o que faz sem contaminar nada.",
  "zero trust": "Zero Trust assume 'nunca confie, sempre verifique'. Cada acesso é autenticado, independente de onde vem.",
  "mfa": "MFA (autenticação de múltiplos fatores) exige 2+ provas de identidade. Bloqueia maioria de invasões por senha.",
  "bcrypt": "bcrypt é uma função de hash de senha lenta e com salt. Mesmo com o banco vazado, senhas não voltam fácil.",
  "argon2": "Argon2 (e scrypt) são hashes de senha modernos, resistentes a GPU/ASIC. Prefira-os a SHA simples.",
  "salt+cost": "Salt é valor aleatório por senha; cost é o trabalho do hash. Juntos impedem tabelas pré-computadas (rainbow).",
  "tls 1.3": "TLS 1.3 é a versão atual de criptografia de transporte. handshake rápido e sem ciphers fracos.",
  "tls handshake": "O handshake TLS negocia chaves e prova identidade. 'https' que você vê no navegador.",
  "rsa": "RSA é criptografia assimétrica (par de chaves). Base de assinatura e troca de chaves, mas dá lugar a ECC.",
  "aes": "AES é o padrão simétrico de blocos. Rápido e seguro; use GCM para autenticar além de cifrar.",
  "gcm": "AES-GCM cifra e autentica numa tacada (AEAD). Detecta adulteração, não só esconde.",
  "forward secrecy": "Forward secrecy troca chaves de sessão efêmeras. Mesmo que a chave longa vaze, conversas passadas ficam seguras.",
  "hash": "Hash reduz dados a um resumo fixo e irreversível. Integridade (checksum) e armazenamento de senha.",
  "encoding≠hash": "Encoding (base64) só transforma; hash resume e não volta. Confundir os dois quebra segurança.",
  "csprng": "CSPRNG é gerador de números aleatórios criptográficos. Seed fraco = chave previsível = inseguro.",
  "side-channel": "Side-channel vaza segredos por tempo, energia ou som, não pelo algoritmo. Constant-time mitiga.",
  "constant-time": "Código constant-time leva o mesmo tempo independente do segredo. Evita vazamento por temporização.",
  "hmac": "HMAC é hash com chave secreta. Prova integridade E autenticidade de uma mensagem.",
  "x.509": "X.509 é o formato de certificados digitais (PKI). O que o TLS e a assinatura de código usam.",
  "ca": "CA (Certificate Authority) emite e assina certificados. A raiz em que todo o HTTPS confia.",
  "key pinning": "Certificate pinning fixa qual certificado esperar. Dificulta MITM, mas exige gestão cuidadosa.",
  "rbac": "RBAC (Role-Based Access Control) dá permissões por papel, não por pessoa. Menos caos em ACLs.",
  "least privilege": "Princípio do menor privilégio: só o acesso estritamente necessário. Limitou, limitou o dano.",
  "secrets": "Segredos (chaves, tokens) nunca vão no código. Use vault/env e rotacione regularmente.",
  "rotate key": "Rotação de chaves troca credenciais periodicamente. Reduz janela de exposição se uma vazar.",
  "hardening": "Hardening endurece o sistema: fecha portas, remove serviços, aplica CIS Benchmark. Superfície de ataque menor.",
  "cis benchmark": "CIS Benchmarks são configurações seguras recomendadas para SO/app. Checklist de hardening.",
  "lynis": "Lynis faz auditoria de segurança local no Linux. Aponta o que endurecer.",
  "firewall": "Firewall filtra tráfego por regras. Default-deny (só o necessário passa) é a postura segura.",
  "proxychains": "Proxychains encadeia proxies para saída anônima. Em lab, isto separa o tráfego do ataque do seu.",
  "chisel": "Chisel é túnel TCP sobre HTTP. Útil em pivoting para alcançar redes internas via host comprometido.",

  // ---------- sistemas / linux ----------
  "kernel": "O kernel é o núcleo do SO: gere processos, memória, dispositivos. Tudo passa por ele.",
  "shell": "Shell é o interpretador de linha de comando (bash/zsh). O jeito de falar com o sistema.",
  "espaço usuário": "Espaço de usuário são os programas fora do kernel. Se um cai, o sistema sobrevive.",
  "distros": "Distribuições empacotam kernel+tools diferentes (Debian, Arch, Fedora). Mesmo Linux, sabores distintos.",
  "arch": "Arch Linux é rolling-release, minimalista e documentado (Wiki). Você monta o sistema do zero.",
  "boot": "Boot é a sequência que sobe o sistema: firmware → bootloader (GRUB) → kernel → initramfs → init.",
  "grub": "GRUB é o bootloader que escolhe qual kernel iniciar. Sem ele, o disco não sobe.",
  "initramfs": "initramfs é o sistema mínimo na RAM que monta o root real e passa o controle ao init.",
  "systemd": "systemd é o init moderno: gerencia serviços, sockets, timers. Unidade .service descreve cada daemon.",
  "ext4": "ext4 é o sistema de arquivos padrão do Linux. Journaling protege contra corrupção em queda de energia.",
  "inode": "inode guarda metadados do arquivo (permissões, blocos) sem o nome. Muitos inodes esgotam antes do espaço.",
  "mount": "mount anexa uma partição/diretório em árvore. fstab monta automaticamente na boot.",
  "fstab": "fstab lista o que montar no boot e opções. Erro aqui pode deixar o sistema sem subir.",
  "/dev": "/dev expõe dispositivos como arquivos (discos, terminais). Em Linux, 'tudo é arquivo'.",
  "partições": "Partições dividem o disco em áreas lógicas. Separar /home, /var evita um flood derrubar tudo.",
  "pid": "PID identifica cada processo. ps/top mostram; kill manda sinal; fork cria filhos.",
  "ps": "ps lista processos. top/atop mostram consumo ao vivo. Base para caçar o que usa CPU/RAM.",
  "top": "top mostra processos em tempo real por uso. triagem de性能 e de recursos.",
  "foreground": "Foreground roda no terminal e bloqueia; background (bg) solta. jobs/ctrl-z gerem.",
  "signals": "Sinais (SIGTERM, SIGKILL) pedem a processos que parem. kill -9 é a última instância.",
  "kill": "kill manda sinal a um PID. SIGTERM pede; SIGKILL força (não pode ser ignorado).",
  "sudo": "sudo executa como outro usuário (root). Loga tudo — rastro de quem fez o quê.",
  "umask": "umask define permissões padrão de novos arquivos. Controla o que nasce world-readable.",
  "chmod": "chmod muda permissões (rwx). Numérico (755) ou simbólico (u+x). Base de segurança de arquivo.",
  "chown": "chown muda dono/grupo do arquivo. Combina com chmod para controle de acesso.",
  "suid": "SUID faz binário rodar como dono (ex.: passwd). Poderoso; abuso é vetor de privesc.",
  "cron": "cron agenda tarefas por tempo. systemd timer é a alternativa moderna, com dependências.",

  // ---------- redes ----------
  "tcp/ip": "TCP/IP é a pilha que faz a internet funcionar. TCP confiável, IP roteia. OSI é o modelo de referência.",
  "osi": "Modelo OSI tem 7 camadas; TCP/IP as compacta. Entender camadas isoladas problemas de rede.",
  "sub-redes": "Sub-redes dividem uma rede em blocos (CIDR). Define quem se fala direto e onde o roteador entra.",
  "cidr": "CIDR (ex.: /24) nota o tamanho da rede em bits. Substituiu classes fixas, mais flexível.",
  "dns": "DNS traduz nome (google.com) em IP. Sem ele, só números. Alvo comum de ataque e tunelamento.",
  "arp/dns": "ARP resolve IP→MAC na LAN; DNS resolve nome→IP. Os dois mapeiam endereços em camadas diferentes.",
  "dhcp": "DHCP entrega IP, máscara e gateway automaticamente. Servidor mal configurado = rede inteira parada.",
  "vlan": "VLAN segmenta a rede por software num mesmo switch. Isola departamentos sem cabos separados.",
  "nat": "NAT esconde a rede interna atrás de um IP público. Permite muitos dispositivos com um IP.",
  "firewall de borda": "Firewall de borda filtra o tráfego de entrada/saída do perímetro. Primeira linha de defesa.",
  "vpn": "VPN cria túnel cifrado sobre a internet. WireGuard é o padrão moderno, leve e rápido.",
  "wireguard": "WireGuard é VPN de código mínimo e auditanível. handshake rápido e curvas modernas.",
  "wireshark": "Wireshark captura e decodifica pacotes. Ver o handshake TCP ao vivo ensina redes de verdade.",
  "tcpdump": "tcpdump captura pacotes na linha de comando. Essencial em servidor sem interface gráfica.",
  "handshake": "Handshake é a negociação inicial (ex.: TCP 3 vias, TLS). Estabelece estado antes de transmitir.",
  "portas": "Portas (0-65535) distinguem serviços num mesmo IP. 80/443 web, 22 SSH, 53 DNS.",
  "roteamento": "Roteamento decide o próximo salto de um pacote. Tabelas e protocolos (BGP, OSPF) mantêm o caminho.",
  "bgp": "BGP é o protocolo que conecta as redes da internet. Erro de rota = blocos inteiros offline.",
  "mtr": "mtr combina ping e traceroute ao longo do tempo. Mostra onde a perda de pacotes acontece.",
  "ping": "ping manda ICMP e mede ida/volta. Teste de conectividade mais básico que existe.",

  // ---------- dados / ml ----------
  "csv": "CSV é texto separado por vírgula. Formato universal para trocar tabelas entre ferramentas.",
  "json": "JSON é texto estruturado chave-valor. A linguagem da web e de APIs modernas.",
  "pandas": "pandas manipula tabelas (DataFrame) em Python: carregar, filtrar, agrupar. O canivete suíço de dados.",
  "nulos": "Valores nulos faltam. dropna remove, fillna preenche. Decidir erro de medição vs ausência real.",
  "duplicados": "Duplicados distorcem contagens e modelos. drop_duplicates limpa antes de analisar.",
  "outliers": "Outliers são pontos extremos. Podem ser erro de medição ou o evento raro que importa — investigue.",
  "padronizar": "Padronizar (normalizar texto, unidades) faz dados de fontes diferentes conversarem.",
  "resumo": "Estatísticas de resumo (média, mediana, desvio) reduzem milhões de linhas a números compreensíveis.",
  "distribuições": "Distribuições descrevem como os valores se espalham (normal, Poisson). Base de inferência.",
  "correlação": "Correlação mede relação linear entre duas variáveis. Correlação ≠ causalidade — cuidado.",
  "cruzamento": "Cruzar tabelas (join/merge) responde perguntas que uma só não responde. O coração da análise.",
  "hipóteses": "Teste de hipóteses pergunta se um efeito é real ou acaso (p-value). Evita ver padrão onde não há.",
  "p-value": "p-value é a chance de ver o resultado se a hipótese nula for verdade. Baixo = efeito improvável ao acaso.",
  "regressão": "Regressão prevê uma variável a partir de outras. Linear é o começo; árvore e rede vêm depois.",
  "overfit": "Overfit é o modelo decorar o treino e falhar no novo. Validação separada detecta.",
  "treino/teste": "Separar treino de teste avalia o modelo em dados que ele não viu. Mede capacidade de generalizar.",
  "features": "Feature engineering cria variáveis úteis a partir das brutas. Muitas vezes vale mais que trocar de modelo.",
  "normalizar": "Normalizar escala variáveis para mesma faixa. Evita que uma grande domine o modelo.",
  "matplotlib": "matplotlib desenha gráficos em Python. seaborn adiciona visual bonito por cima.",
  "seaborn": "seaborn é camada estatística sobre matplotlib. Gráficos de distribuição/correlação em poucas linhas.",
  "numpy": "numpy faz álgebra numérica rápida com arrays. Base de quase toda biblioteca científica em Python.",

  // ---------- engenharia de dados / padroes ----------
  "cqrs": "CQRS separa quem escreve (command) de quem lê (query). Models diferentes para cada lado escalam melhor.",
  "idempotência": "Idempotência garante que repetir a operação não muda além da primeira vez. Essencial com retries.",
  "idempotente": "Operação idempotente: f(f(x)) == f(x). Ex.: PUT é idempotente, POST não. Retry seguro.",
  "race-condition": "Race condition acontece quando o resultado depende da ordem de execução. lost update clássico.",
  "dlq": "Dead Letter Queue guarda mensagens que falharam de processar. Isola o lixo e permite reprocessar.",
  "dual-write": "Dual-write escreve em duas fontes ao mesmo tempo — arriscado. Outbox pattern resolve com CDC.",
  "cache-stampede": "Cache stampede é quando many pedem ao mesmo tempo algo expirado e derrubam o banco. Lock/jitter ajudam.",
  "rate-limit": "Rate limit limita requisições por janela. Protege contra sobrecarga e abuso (DDoS barato).",
  "time-attack": "Timing attack mede tempo de operação para inferir segredos. Constant-time é a defesa.",
  "poison-message": "Poison message falha sempre e trava o consumidor em loop. DLQ + validação antecipada evitam.",
  "at-least-once": "At-least-once entrega pode duplicar; at-most-once pode perder. Escolha exige idempotência no consumidor.",
  "outbox": "Outbox pattern grava evento na mesma transação do dado e o envia depois. Consistência sem dual-write.",
  "saga": "Saga coordena transações distribuídas com compensação. Se um passo falha, desfaz os anteriores.",
  "event sourcing": "Event sourcing guarda o log de eventos como fonte da verdade. Rebuild de estado a qualquer momento.",
  "2pc": "Two-Phase Commit tenta transação distribuída com coordinator. Robusto mas lento e bloqueia.",
  "kafka": "Kafka é log de eventos distribuído e durável. Desacopla produtores de consumidores em alta escala.",
  "redis": "Redis é cache/store em memória. INCR, EXPIRE, locks distribuídos — velocidade para o que é quente.",
  "mvcc": "MVCC (Multi-Version Concurrency Control) mantém versões para leitores não bloquearem escritores.",
  "acid": "ACID garante transações confiáveis: Atomicidade, Consistência, Isolamento, Durabilidade.",
  "sql": "SQL é a linguagem de banco relacional. SELECT/INSERT/UPDATE; JOIN liga tabelas.",
  "nosql quando": "NoSQL brilha em escala horizontal e esquema flexível; relacional quando consistência e joins importam.",
  "star schema": "Star schema organiza DW em fatos e dimensões. Otimizado para agregar e consultar analytics.",
  "parquet": "Parquet é formato colunar comprimido. Rápido para analytics em big data (menos I/O).",
  "etl": "ETL extrai, transforma e carrega dados. ELT inverte a ordem (carrega cru e transforma depois).",
  "streaming": "Streaming processa dados em movimento (não em lote). Kafka/Flink para tempo real.",
  "airflow": "Airflow orquestra pipelines em DAGs com agendamento. O padrão de data engineering.",

  // ---------- fallbacks por categoria geral ----------
  "api": "API é a interface que um sistema expõe para outros usarem. Contratos claros evitam acoplamento.",
  "auth": "Auth (autenticação) prova quem você é; Authz (autorização) diz o que pode. JWT/OAuth são comuns.",
  "authz": "Autorização decide o que um usuário pode fazer após autenticado. RBAC é a forma habitual.",
  "cli test": "Testar pela CLI exercita o binário como usuário real faria. Automatizável e honesto.",
  "backup": "Backup é cópia de segurança. 3-2-1 (3 cópias, 2 mídias, 1 offsite) é a regra de ouro.",
  "banco": "Banco de dados armazena dados de forma consultável. Relacional (SQL) ou não-relacional (NoSQL).",
  "dados": "Dados são a matéria-prima: coletar, limpar e analisar transforma observação em decisão.",
  "engenharia": "Engenharia é aplicar princípios para construir sistemas que funcionam e se mantêm no tempo.",
  "segurança": "Segurança é proteger confidencialidade, integridade e disponibilidade. Defesa em profundidade.",
  "red": "Red Team simula o atacante para encontrar falhas antes do adversário real. Sempre com autorização.",
  "blue": "Blue Team defende: detecta, responde e endurece. O contraponto que torna o ataque difícil.",
  "lab": "Lab é o ambiente isolado e seu onde se pratica sem risco ao real. Regras de engajamento primeiro.",
  "ética": "Ética em segurança é não tocar no que não é seu sem autorização por escrito. A lei existe.",
  "log": "Logs registram o que aconteceu. Sem logs não há investigação, auditoria ou detecção.",
  "monitor": "Monitorar é coletar métricas e alertar anomalias. O que mantém o sistema vivo e visível.",
  "deploy": "Deploy coloca o código em produção. Automatizar reduz erro humano e acelera entrega.",
  "teste": "Testes automatizados provam que o código faz o prometido. Sem eles, cada mudança é um risco.",
  "qualidade": "Qualidade de código é legibilidade, cobertura e design. Técnica dívida cobra juros depois.",
  "refatorar": "Refatorar melhora a estrutura sem mudar comportamento. Pequenas mudanças contínuas evitam refactor gigante.",
  "arquitetura": "Arquitetura são as decisões de alto nível (divisão em serviços, dados, fronteiras). Define o futuro do sistema.",
  "modelos": "Modelos são representações simplificadas da realidade. Em ML, aprendem padrão a partir de dados.",
  "integração": "Integração conecta sistemas para trabalharem juntos. Contratos e retries tornam-na resiliente.",
  "observabilidade": "Observabilidade é entender o sistema interno pelos sinais externos (logs, métricas, traces).",
  "automação": "Automação tira tarefas repetitivas do humano. Script ou ferramenta faz de forma repetível.",
  "incidente": "Incidente é qualquer quebra de serviço esperado. Responder bem é uma disciplina (IR).",
  "documentar": "Documentar preserva contexto para quem chega depois. README, ADR e runbooks valem ouro.",
  "aprender": "Aprender na prática (fazer, errar, corrigir) fixa mais que ler. Por isso este roadmap é exercício."
};

/* Gera explicacoes para um modulo a partir da lista de topicos (start).
   Casamento de termos com borda de palavra (evita "def" casar em "definicao") + fallback. */
function explainStage(startArray) {
  const out = [];
  const seen = new Set();
  (startArray || []).forEach(topic => {
    const t = topic.toLowerCase();
    let matched = null;
    const keys = Object.keys(MAP).sort((a, b) => b.length - a.length);
    for (const k of keys) {
      if (seen.has(k)) continue;
      // termo deve ser palavra inteira OU prefixo seguido de nao-letra (ex.: "def" em "def x", mas nao em "definicao")
      const re = new RegExp("(^|[^a-z0-9])" + k.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "([^a-z0-9]|$)");
      if (re.test(t)) { matched = k; break; }
    }
    if (matched) {
      seen.add(matched);
      out.push({ topic: topic, text: MAP[matched] });
    } else {
      const limpo = topic.replace(/\.$/, "");
      out.push({ topic: topic, text: `${limpo.charAt(0).toUpperCase() + limpo.slice(1)} é um tópico deste módulo — domine-o na prática antes de avançar.` });
    }
  });
  return out;
}

module.exports = { MAP, explainStage };
