/* explain.js — explicacoes didaticas densas por etapa.
   Formato esperado pelo server.js/loadAreas:
     explainStage(areaId, stageId, start) -> [{ topic, text }, ...]
   O app.js renderExplain consome e.topic e e.text. */
(function () {
  const EXPLAIN = {
    "python/s1": [
      { topic: "Instale Python 3.14 e rode o REPL.", text: "O REPL (Read-Eval-Print Loop) é o interpretador interativo: voce digita uma expressao, ele executa e mostra o resultado na hora. Instalar a versao mais recente garante recursos de linguagem e seguranca; rode `python3` no terminal para entrar e `exit()` ou Ctrl-D para sair. Use o REPL como laboratorio rapido para testar sintaxe antes de escrever arquivos." },
      { topic: "Entenda variáveis e os tipos básicos.", text: "Em Python voce nao declara o tipo: a variavel aponta para um objeto e o tipo vem do valor. Os basicos sao int (inteiros arbitrariamente grandes), float (ponto flutuante), str (texto imutavel), bool (True/False) e None. Tipos errados sao a causa numero um de bugs iniciantes: '42' (string) != 42 (int), e somar os dois da erro de concatenacao/tipo." },
      { topic: "Domine list/dict/set/tuple.", text: "list [] e mutavel e ordenada (use para sequencias que mudam); tuple () e imutavel (otimo para chaves de dict e dados que nao devem mudar); dict {} mapeia chave->valor com busca O(1) (use para registros e caches); set {} guarda valores unicos e faz operacoes de conjunto (uniao, intersecao). Escolher a estrutura certa torna o codigo mais rapido e claro." },
      { topic: "Laços e if/elif.", text: "Controle de fluxo: if/elif/else decide caminhos; for itera sobre sequencias (for x in lista); while repete enquanto a condicao for verdadeira. Evite while sem condicao de parada — ele vira loop infinito. Prefira for sempre que souber o tamanho da colecao; use while para esperar eventos ou condicoes dinamicas." },
      { topic: "Compreensões de lista.", text: "A compreensao [x for x in seq if cond] cria listas de forma concisa e geralmente mais rapida que loops手动. O padrao e: resultado para cada item em origem se filtro. Existe tambem para dict, set e generator (com parenteses). Dominar isso elimina dezenas de linhas de codigo repetitivo." },
      { topic: "Use o REPL como laboratório.", text: "Antes de escrever um script, teste a logica no REPL: veja o que cada expressao retorna, entenda erros de imediato e so depois transfira para um arquivo .py. Isso encurta o ciclo de feedback e previne bugs. Dica: `_` no REPL guarda o ultimo resultado." }
    ],
    "python/s2": [
      { topic: "Defina funções com def.", text: "Funcoes agrupam logica reutilizavel: `def nome(params):` seguido de corpo indentado. Elas tornam o codigo modular, testavel e legivel. Regra de ouro: uma funcao faz uma coisa bem feita e tem nome que diz o que faz." },
      { topic: "Parâmetros posicionais e nomeados.", text: "Parametros posicionais sao lidos na ordem; nomeados (kwargs na chamada) deixam explicito o que cada valor significa e permitem defaults. Ex: `def f(a, b=2)` — b e opcional. Misturar bem os dois torna APIs claras: `f(10, b=5)` e mais legivel que `f(10,5)`." },
      { topic: "*args e **kwargs.", text: "*args captura argumentos posicionais extras em uma tupla; **kwargs captura os nomeados em um dict. Sao essenciais para escrever wrappers e funcoes que repassam parametros (ex: decoradores, adapters). Use com parcimonia: abusar esconde a assinatura e dificulta a manutencao." },
      { topic: "Escopo LEGB.", text: "Python resolve nomes na ordem Local -> Enclosing (funcao externa) -> Global -> Built-in. Uma variavel criada dentro de uma funcao e local e some ao sair; para modificar global voce precisa de `global` e para fechar sobre variavel da funcao externa usa `nonlocal`. Entender LEGB evita o classico bug de 'variavel nao foi alterada'." },
      { topic: "Recursão vs iteração.", text: "Recursao e quando a funcao chama a si mesma reduzindo o problema (ex: fatorial, Fibonacci). Elegante, mas cada chamada usa a pilha — recursao profunda estoura (RecursionError). Iteracao com loop e quase sempre mais eficiente em Python; use recursao so quando o modelo for natural (arvores, dividir-e-conquistar)." },
      { topic: "Docstrings e type hints.", text: "Docstring (string logo apos def) documenta o que a funcao faz para humanos e ferramentas. Type hints (def f(x: int) -> str) documentam tipos para o mypy e editores, sem custo em runtime. Juntos, tornam o codigo autodocumentado e pegam erros de tipo antes de rodar." }
    ],
    "python/s3": [
      { topic: "Type hints com mypy.", text: "Type hints declaram os tipos esperados (def f(x: int) -> str) e o mypy faz checagem estatica, pegando erros como passar str onde se espera int sem precisar rodar o programa. Não são obrigatorios, mas em projetos reais reduzem bugs e melhoram a leitura. Comece aos poucos: anote funcoes publicas primeiro." },
      { topic: "Crie pacote com pyproject.", text: "Um pacote e um diretorio com __init__.py (ou pacote de namespace) e um pyproject.toml que descreve nome, versao, dependencias e como buildar. O padrão moderno (PEP 621) usa [project] no pyproject.toml. Empacotar certo permite instalar com pip e reutilizar o codigo em outros projetos." },
      { topic: "__init__ e imports.", text: "O __init__.py marca um diretorio como pacote e pode expor a API publica (from meu_pacote import x). Imports absolutos (pacote.modulo) sao mais claros; imports relativos (from . import x) servem dentro do pacote. Import circular acontece quando A importa B e B importa A — resolva movendo codigo para um terceiro modulo ou importando dentro da funcao." },
      { topic: "venv para isolar.", text: "Ambientes virtuais (python3 -m venv .venv) isolam as dependencias de cada projeto, evitando o pesadelo de 'funciona na minha maquina'. Sempre ative o venv (source .venv/bin/activate) antes de pip install. Nunca instale pacotes globalmente em producao." },
      { topic: "pyproject moderno.", text: "O pyproject.toml unificou configuracao de build, ferramentas (ruff, mypy, pytest) e metadados num so arquivo. Antes havia setup.py, setup.cfg e tox.ini espalhados. Adotar pyproject deixa o projeto padronizado e facil de rodar em CI." },
      { topic: "Scripts de entrypoint.", text: "Um entrypoint declara um comando de terminal que chama sua funcao (em [project.scripts] no pyproject). Assim o usuario roda `minha-cli` em vez de `python -m meu_pacote`. Isso e o que torna suas ferramentas instalaveis e utilizaveis de qualquer lugar." }
    ],
    "python/s4": [
      { topic: "class, __init__, self.", text: "Classes sao moldes para criar objetos que juntam dados (atributos) e comportamento (metodos). __init__ e o construtor que roda na criacao; self e a referencia ao proprio objeto (obrigatorio no primeiro parametro de metodos). OOP ajuda a modelar o dominio: uma Conta, um Produto, um Usuario viram objetos coesos." },
      { topic: "Herança e super().", text: "Heranca permite que uma classe reaproveite e especialize outra (ContaPoupanca herda de Conta). super() chama o metodo da classe mae sem acoplar ao nome dela, essencial em construtores e overrides. Use heranca para 'e-um' (Cachorro e Animal), nao para reuso casual de codigo." },
      { topic: "@property e dunder.", text: "@property transforma um metodo em atributo somente-leitura (ou com setter), permitindo validar ao atribuir sem mudar a API. Metodos dunder (__init__, __str__, __len__) sao 'magigos' chamados pelo interpretador em operacoes naturais (len, print). Usa-los torna objetos que se comportam como tipos nativos." },
      { topic: "dataclasses.", text: "O decorador @dataclass gera automaticamente __init__, __repr__, __eq__ e mais a partir de anotacoes de atributos. Substitui dezenas de linhas de boilerplate para classes de dados (Produto, Config). E a forma moderna e limpa de modelar estruturas de dados simples." },
      { topic: "Padrão Strategy/Factory.", text: "Strategy encapsula algoritmos trocaveis (ex: DescontoPercentual vs DescontoFixo) atras de uma mesma interface, permitindo mudar comportamento em runtime. Factory centraliza a criacao de objetos. Padrões dao vocabulario comum e evitam if/elif gigantes — mas so os use quando resolvem um problema real, nao por estetica." },
      { topic: "ABC para interfaces.", text: "ABC (abstract base class) define interfaces: metodos abstratos que subclasses obrigatoriamente implementam. Isso garante contratos (ex: toda 'Storage' tem save/load) e ajuda o mypy a pegar implementacoes faltantes. Use ABC para forcar consistencia em familias de classes." }
    ],
    "python/s5": [
      { topic: "Event loop e corrotinas.", text: "asyncio roda milhares de tarefas aparentemente simultaneas em uma so thread, trocando de tarefa quando uma aguarda I/O (await). O event loop e o agendador. Isso brilha em redes (muitas requisicoes lentas), mas NAO acelera CPU-bound — para isso use processos." },
      { topic: "async def / await.", text: "async def define uma corrotina; await suspende ela ate a operacao assincrona terminar, liberando o loop para outra tarefa. Regra: so se chama corrotina com await ou asyncio.run. Misturar codigo sync e async sem cuidado gera 'event loop is closed' ou travamento." },
      { topic: "asyncio.gather.", text: "gather executa varias corrotinas concorrentemente e retorna os resultados juntos. E o que faz o download de 10 paginas ser 10x mais rapido que em sequencia. Para I/O intenso, concurrent e o ganho real; meca o tempo com time.perf_counter para provar a banca." },
      { topic: "multiprocessing p/ CPU.", text: "Python tem o GIL (Global Interpreter Lock) que impede threads de rodar Python em paralelo na CPU. Para trabalho CPU-bound (processar imagens, calculo), use multiprocessing: cada processo tem seu proprio interpretador e GIL. Escolha certo: asyncio para I/O, multiprocessing para CPU." },
      { topic: "aiohttp p/ requests.", text: "aiohttp e um cliente/servidor HTTP assincrono; combine com asyncio.gather para fazer centenas de requisicoes sem bloquear. Evite requests (sincrono) dentro de corrotinas — ele trava o loop. Para APIs externas, assincrono e o caminho escalavel." },
      { topic: "GIL e limites.", text: "O GIL e a razao de Python nao usar threads para CPU paralela. Entenda isso para nao prometer performance que o codigo nao entrega. Solucoes: multiprocessing, ou bibliotecas que liberam o GIL (numpy, ctypes, cython). Saber o limite e o que separa I/O-bound de CPU-bound." }
    ],
    "python/s6": [
      { topic: "pandas load CSV/JSON.", text: "pandas.read_csv/read_json carregam dados em DataFrames (tabelas rotuladas). E a ferramenta padrao para analise: selecao, filtragem e agregacao em uma linha. Sempre inspecione com .head(), .shape e .info() ao carregar — dados sujos quebram analises silenciosamente." },
      { topic: "Limpeza: dropna/fillna.", text: "Dados reais tem lacunas. dropna remove linhas/colunas vazias; fillna preenche com valor (media, 0, ffill). A escolha errada distorce conclusoes: preencher com 0 pode mascarar ausencia. Documente e justifique cada limpeza — a banca vai perguntar." },
      { topic: "groupby e merge.", text: "groupby agrupa por coluna e aplica agregacao (soma, media) — ex: vendas por mes. merge junta DataFrames como JOIN de SQL (on=chave). Sao as operacoes que transformam dados brutos em respostas de negocio. Confira chaves e tipos antes de mergear para nao duplicar linhas." },
      { topic: "numpy arrays.", text: "numpy opera sobre arrays tipados em C, muito mais rapido que loops em lista para matematica. pandas e construido sobre numpy. Vetorizacao (operar em arrays inteiros de uma vez) elimina loops lentos. Para 'matematica real' na banca, numpy e a base." },
      { topic: "matplotlib básico.", text: "matplotlib.pyplot desenha graficos (plot, bar, hist). Visualizacao e como voce comunica descobertas: um grafico de tendencia vale mais que uma tabela. Sempre rotule eixos, titulo e legenda; graficos sem contexto enganam." },
      { topic: "métricas reais.", text: "Nao basta 'plotar': calcule media, mediana, desvio, correlacao (df.corr()). Entenda o que cada metrica diz e suas armadilhas (media escondida por outliers; correlacao nao implica causalidade). A banca quer raciocinio estatistico, nao so imagem bonita." }
    ],
    "python/s7": [
      { topic: "open() e context manager.", text: "with open('a.txt') as f: abre e FECHA o arquivo automaticamente, mesmo se der erro. Esquecer de fechar vaza handles e corrompe dados. O context manager (protocolo __enter__/__exit__) e o padrao seguro para qualquer recurso (arquivo, conexao, lock)." },
      { topic: "json dump/load.", text: "JSON e o formato universal de troca de dados (APIs, config). json.dump serializa objeto Python em arquivo; json.load faz o inverso. Limite: so tipos basicos (dict, list, str, int, float, bool, None). Para dados complexos, use dataclasses + custom encoder." },
      { topic: "csv reader/writer.", text: "csv.DictReader lê cada linha como dict pelas colunas; csv.writer escreve. E essencial para dados tabulares legados. Cuidado com delimitador e encoding (use encoding='utf-8' explicito, senao quebra acentos). Trate aspas e virgulas dentro de campos." },
      { topic: "pathlib.", text: "pathlib.Path e a API orientada a objetos para caminhos de arquivo, muito mais legivel que os string hacks do os.path. p.exists(), p.glob('*.py'), p.read_text(). E multiplataforma (Windows/Linux) sem voce pensar em barras." },
      { topic: "pickle com cuidado.", text: "pickle serializa objetos Python arbitrarios — mas carregar pickle de fonte nao confiavel executa codigo arbitrario (RCE). Nunca unpickle dados de terceiros. Para dados seguros use JSON; para modelos ML, controle a origem rigorosamente." },
      { topic: "yaml para config.", text: "YAML e legivel para humanos e comum em configs (Docker Compose, CI). Use PyYAML para ler. Atencao: YAML faz type coercion silenciosa (yes vira True) e tem riscos de parse; prefira JSON para confiabilidade, YAML para quem vai editar a mao." }
    ],
    "python/s8": [
      { topic: "pytest básico.", text: "pytest descobre funcoes test_*, onde cada assert verifica um comportamento. Testes sao a rede de seguranca do codigo: provam que funciona e avisam quando quebra. Escreva o teste junto com a funcao, nao depois." },
      { topic: "TDD: teste antes.", text: "Test-Driven Development: escreva o teste que falha (red), implemente o minimo para passar (green), refatore (refactor). Isso forca clareza de requisitos e deixa refatorar sem medo. A banca valoriza codigo com testes, nao so 'que roda'." },
      { topic: "fixtures.", text: "@pytest.fixture cria dependencias de teste (um banco fake, um usuario) reaproveitadas e isoladas. Evita duplicar setup e mantem testes independentes. Bons fixtures = testes rapidos e confiaveis; fixtures pesadas deixam a suite lenta." },
      { topic: "coverage.", text: "coverage mede qual fração do codigo os testes exercitam (--cov). 100% nao e garantia de corretude, mas baixo coverage e certeza de areas nao testadas. Use como mapa do que falta, nao como trofeu." },
      { topic: "ruff/flake8.", text: "Linters apontam codigo morto, imports nao usados, estilo. ruff e o moderno (rapido, em Rust) que substitui flake8+isort+black. Rodar lint no CI impede que codigo ruim entre. Lint limpo e sinal de profissionalismo para a banca." },
      { topic: "mypy em CI.", text: "mypy no CI garante que os type hints continuem validos a cada commit. Tipos + testes + lint formam a 'barreira de qualidade' de engenharia seria. Automatizar isso (GitHub Actions) e o que separa projeto de brincadeira de projeto de portifolio real." }
    ],
    "python/s9": [
      { topic: "REST verbs e status.", text: "REST usa verbos HTTP (GET le, POST cria, PUT/PATCH atualiza, DELETE remove) e codigos de status (2xx sucesso, 4xx erro do cliente, 5xx do servidor). Uma API bem feita e previsivel: o cliente sabe o que esperar. Use 201 em criacao, 404 quando nao acha, 400 em entrada invalida." },
      { topic: "FastAPI + pydantic.", text: "FastAPI usa pydantic para validar o corpo da requisicao automaticamente e gerar documentacao OpenAPI. Voce declara o modelo (class Item: name: str) e ele rejeita entrada errada com 422 antes do seu codigo rodar. Rapido (async) e produtivo — ideal para APIs reais." },
      { topic: "Validação de entrada.", text: "NUNCA confie no cliente. Valide tipo, tamanho, intervalo e permissao de toda entrada. Pydantic faz isso na borda; depois, cheque autorizacao. Entrada nao validada e a porta de entrada de injecao e quebra — a banca vai procurar isso." },
      { topic: "Auth por token.", text: "Autentique com token (BearerJWT) ou session, e autorize por requisito. Nao exponha dados de outros usuarios: sempre filtre por user_id do token. Middleware de auth centraliza a regra e evita esquecer em um endpoint." },
      { topic: "Cliente requests.", text: "Para consumir APIs, requests (sync) ou httpx (async) fazem GET/POST com retry e timeout. Sempre defina timeout (senao trava) e trate falhas (raise_for_status). Um cliente robusto com retry torna seu sistema resiliente a instabilidade de rede." },
      { topic: "OpenAPI.", text: "FastAPI gera /docs automatico (Swagger). Documentacao viva da API ajuda quem consome e serve de especificacao. Teste o /docs e os esquemas — API sem documentacao e API que ninguem usa." }
    ],
    "python/s10": [
      { topic: "Escolha projeto útil.", text: "O melhor portfolio e um projeto que resolve um problema real seu (organizador de pastas, CLI de estudo, bot de lembrete). Utilidade > demonstracao vazia. A banca pergunta 'por que isso existe?' — tenha resposta." },
      { topic: "Aplique TDD.", text: "Comece o projeto com testes, nao no fim. Isso forca design limpo e deixa refatorar sem medo. Um repo com testes e evidencia de engenharia, nao so script que 'roda na sua maquina'." },
      { topic: "README pt-BR.", text: "O README e o cartao de visitas: o que e, como instalar (pip install -e . ou venv), como usar, como contribuir. Escreva em pt-BR para a banca brasileira, com exemplos copy-paste. README ruim = projeto invisivel." },
      { topic: "Git commits pequenos.", text: "Commits atomicos (uma mudanca logica cada) com mensagens claras (verbo no imperativo) mostram evolucao real. A banca revisa o historico do git — um monte de 'update' ou commit gigante transmite falta de metodo." },
      { topic: "Publique no GitHub.", text: "gh repo create --public publica com licenca (MIT). Licenca explicita diz 'pode usar'. Um repo publico com CI verde, testes e README e o que abre portas para vagas e para a banca de seguranca/engenharia." },
      { topic: "Demonstre à banca.", text: "Prepare um pitch de 5 min: problema -> solucao -> como testa -> como roda. Mostre o codigo, nao so slide. A banca quer ver raciocinio e execucao, nao decoracao. Pratique o demo ate fluir." }
    ],
    "red/s1": [
      { topic: "Leia Lei 12.737/12.", text: "A 'Lei Carolina Dieckmann' tipifica crimes contra computador no Brasil: invadir dispositivo alheio, interceptar dados, divulgar senha. Penas de prisao. Regression testing, pentest e estudo SO sao legais; acessar sistema de terceiro sem autorizacao NUNCA. Leia e entenda os limites antes de qualquer lab." },
      { topic: "Monte lab isolado.", text: "Lab isolado = maquinas virtuais suas, em rede privada ou NAT, sem rota para a internet externa. Assim voce pode praticar exploits sem risco legal nem colateral. Metasploitable, DVWA e WebGoat rodam localmente. Isolamento e a fronteira entre estudo e crime." },
      { topic: "Recon passivo/ativo.", text: "Recon passivo (OSINT, whois, certificados) nao toca o alvo e e menos intrusivo. Recon ativo (nmap, scanner) envia pacotes e pode ser detectado/ilegal fora do seu lab. Sempre documente o escopo: o que voce pode e o que nao pode tocar." },
      { topic: "Documente escopo.", text: "Escopo e o contrato de autorizacao: quais IPs, quais horarios, o que e permitido. Sem escopo por escrito, qualquer teste e invasao. Para a banca e para o cliente, documentacao de escopo e prova de profissionalismo e de legalidade." },
      { topic: "Autorização por escrito.", text: "Nunca teste sistema que nao seja seu ou explicitamente autorizado por escrito. 'O dono deixou' de boca nao conta. Para fins academicos, use apenas seus proprios labs. Autorizacao e a diferenca entre pesquisador e atacante." },
      { topic: "Alvo simulado ético.", text: "Use alvos deliberadamente vulneraveis (DVWA, WebGoat, labs da HackTheBox na sua maquina). Eles existem para aprender. Apontar ferramenta para site real 'por curiosidade' e crime e quebra a carreira. Etica primeiro, sempre." }
    ],
    "red/s2": [
      { topic: "Enumere subdomínios/portas.", text: "Enumeracao mapeia a superficie de ataque: subdominios (amass, sublist3r), portas e servicos (nmap -sV). Em lab, isso revela o que esta exposto. Na vida real, so com autorizacao. Saber o que existe e o primeiro passo de qualquer teste." },
      { topic: "OWASP Top 10.", text: "O OWASP Top 10 e o catalago das 10 vulnerabilidades web mais criticas (injecao, quebra de auth, XSS, etc). E a biblia do pentester web e a referencia que a banca espera que voce conheca. Estude cada item com exemplo e mitigacao." },
      { topic: "Burp/ZAP.", text: "Burp Suite e ZAP interceptam e modificam requisicoes HTTP, permitindo testar parametros, cookies e fluxos. O proxy e onde voce ve o que o browser realmente manda. Dominar o interceptador e prerequisito para achar bugs web." },
      { topic: "WebGoat local.", text: "WebGoat e uma app de proposito vulneravel para praticar SQLi, XSS, etc localmente. Rode em docker na sua maquina. E o lugar seguro para aprender o impacto real de cada falha sem cometer crime." },
      { topic: "SQLi/XSS.", text: "SQL Injection injeta SQL na consulta (select * from u where id=... OR 1=1) e vaza/altera dados — mitigue com prepared statements. XSS injeta script no navegador da vitima — mitigue com escape de saida e CSP. Sao as falhas mais classicas e mais cobradas." },
      { topic: "Relatório CVSS.", text: "CVSS (Common Vulnerability Scoring System) quantifica severidade (0-10) por vetores (acesso, complexidade, impacto). Relatorio com CVSS e evidencia traduz 'achei um bug' em 'risco de negocio' para o cliente/banca. Aprenda a calcular e justificar." }
    ],
    "red/s3": [
      { topic: "Proxychains em ambiente de teste.", text: "proxychains roteia o trafego de uma ferramenta por um proxy/SOCKS, escondendo sua origem. EM LAB, ensina o conceito de ofuscar origem; em producao sem autorizacao e evasao ilegal. Use apenas em seus proprios ambientes e documente o 'por que'." },
      { topic: "pivoting SSH/chisel.", text: "Pivoting e usar uma maquina comprometida como ponte para alcancar redes internas (ssh -L/-D, chisel socks). Em lab ensina movimentacao lateral; na rede alheia e intrusao. Aprenda a topologia, nao so o comando." },
      { topic: "relatório exec+técnico.", text: "Relatorio executivo fala de impacto e risco para quem decide (negocio); o tecnico detalha passos e provas para quem corrige. Um bom relatório tem os dois. A banca quer ver que voce comunica para audiencias diferentes." },
      { topic: "detecção pelo blue.", text: "Pense azul: o que gera log? autenticacao falha, conexoes estranhas, picos. Entender como o defensor detecta e o que separa um teste de um ataque real e o que torna seu relatório acionavel." },
      { topic: "Contas/IP por ambiente.", text: "Em lab, separe contas e IPs por ambiente para nao confundir o que e seu do que e alvo. Isso tambem evita vazar dados reais e facilita demonstrar o cenario de forma limpa e reproduzivel para a banca." },
      { topic: "Provedor de proxy (exemplo).", text: "Na pratica real de teste autorizado, usa-se proxies rotativos para nao sobrecarregar um IP (ex: SOAX). EM LAB, isso e apenas conceito: entenda que o defensor ve origem; o atestado e a diferenca entre simulacao e abuso. Nunca use contra alvo nao autorizado." }
    ],
    "red/s4": [
      { topic: "Pilha e registradores.", text: "A pilha (stack) guarda enderecos de retorno e variaveis locais; registradores como RIP apontam onde o codigo executa. Entender isso e a base da exploracao de binarios: se voce sobrescrever o endereco de retorno, muda o fluxo. Estude em C e gdb, em lab." },
      { topic: "ASLR/NX/canary.", text: "ASLR randomiza enderecos, NX marca memoria como nao-executavel e canary detecta estouro de pilha. Sao mitigacoes que tornam exploits dificies. Entender cada um e necessario para planejar contornos e, mais importante, para propor defesas." },
      { topic: "overflow em lab.", text: "Buffer overflow escreve alem do buffer, sobrescrevendo dados vizinhos. EM LAB (programa C vulneravel + gdb) voce aprende o mecanismo e o impacto (RCE). Na vida real, e a vulnerabilidade classica de RCE — e por isso deve ser estudada com seriedade e isolamento." },
      { topic: "linpeas/winpeas.", text: "linpeas/winpeas sao scripts que enumeram automaticamente vetores de privilegio local (permissoes erradas, cron jobs, SUID). Em lab ajudam a entender 'como um usuario comum vira root'. Use para aprender, documentando cada vetor e sua mitigacao." },
      { topic: "CVE em lab.", text: "CVE (Common Vulnerabilities and Exposures) cataloga falhas conhecidas. Praticar exploit de CVE antigo em VM vuln (Metasploitable) ensina o ciclo descoberta->exploit->impacto. Nunca aponte contra sistemas reais; CVE e para corrigir e aprender, nao para atacar." },
      { topic: "mitigação.", text: "Para cada exploit, a contraparte: stack canary, ASLR, NX, atualizacao de patch, menor privilegio. A banca de seguranca quer VER VERMELHO E AZUL: encontrar a falha e propor a defesa. Sempre feche o ciclo com hardening." }
    ],
    "red/s5": [
      { topic: "Estrutura AD.", text: "Active Directory e o servico de diretorio da Microsoft: usuarios, grupos, maquinas e politicas centralizados num dominio. Dominar a estrutura (DC, OU, grupos) e o prerequisito para entender qualquer ataque e defesa AD." },
      { topic: "Kerberos na teoria.", text: "Kerberos e o protocolo de auth do AD: TGT (ticket de concessao) e TGS (ticket de servico) com chaves de criptografia. Entender o handshake explica por que certos ataques funcionam. Estude a teoria antes de rodar ferramenta alguma." },
      { topic: "AS-REP/kerberoasting lab.", text: "AS-REP roasting ataca contas sem preauth (que podem pedir TGT sem senha); kerberoasting quebra o ticket TGS para achar a senha do servico. EM LAB, ensina o mecanismo e a mitigacao (senhas fortes, preauth). Nunca fora do seu ambiente." },
      { topic: "bloodhound.", text: "BloodHound mapeia relacoes de AD num grafo, revelando caminhos de ataque (quem e admin de quem). E a ferramenta que transforma enumeracao manual em analise visual. Use para entender o 'ataque de caminho' e propor segmentacao." },
      { topic: "privesc AD.", text: "Privesc em AD e subir de usuario comum a dominio admin aproveitando relacoes (membership, delegao). Em lab, voce aprende como isso acontece e como a segmentacao e o principio do menor privilegio impedem. Documente o grafo de risco." },
      { topic: "detecção.", text: "O defensor detecta kerberoasting por volume de pedidos TGS, AS-REP por contas sem preauth e BloodHound por consultas LDAP anormais. Sempre apresente o lado azul: logs, SIEM, alertas. Isso e o que eleva o relatorio." }
    ],
    "red/s6": [
      { topic: "Por que phishing funciona.", text: "Phishing explora urgencia, autoridade e erro humano, nao so tecnica. Entender a psicologia (engenharia social) e o que torna um ataque eficaz e o que permite defender por conscientizacao. Estude o vetor para combater, nao para praticar contra terceiros." },
      { topic: "Template de simulação.", text: "Campanhas de simulacao (GoPhish) treinam usuarios em ambiente controlado e autorizado. O template e a mensagem de teste. Use apenas com autorizacao da organizacao e em dominio de teste — nunca contra pessoas reais fora do escopo." },
      { topic: "Domínio de teste.", text: "Use um dominio/documento explicitamente de simulacao, separado de producao. Isso evita enganar usuarios de verdade e mantem o lab etico. A banca quer ver controle de escopo, nao engenharia social real." },
      { topic: "Indicadores visuais.", text: "Ensine a identificar phishing: remetente estranho, urgencia, links que nao batem, erros de portugues, pedido de senha. Treinar o olho do usuario e a defesa tecnica (SPF/DKIM/DMARC) que valida remetente. Conscientizacao + tecnica." },
      { topic: "Relatório de conscientização.", text: "O resultado de uma simulacao e a taxa de cliques por grupo e o que treinar. Relate para o cliente/banca como evidencia de risco humano e plano de melhoria. Isso e defesa, nao ataque." },
      { topic: "Nunca externo.", text: "Regra de ouro: simulacoes somente em ambiente autorizado e de teste. Apontar phishing para pessoas reais e ilegal e destrói a confianca. A banca de seguranca exige que voce demonstre etica antes de tecnica." }
    ],
    "red/s7": [
      { topic: "Tipos de malware.", text: "Virus, worm, trojan, ransomware e spyware diferem em como se espalham e o que fazem. Entender a classificacao ajuda a defesa (quais controles bloqueiam cada vetor). Estude o comportamento, nao para criar, mas para detectar e erradicar." },
      { topic: "Sandbox isolada.", text: "Uma sandbox (VM descartavel, sem rede) e o unico lugar para analisar amostras. Ela isola o dano e permite observar comportamento. NUNCA analise malware na sua maquina real ou com rede — o risco de escapar e real." },
      { topic: "Comportamento vs assinatura.", text: "Deteccao por assinatura (hash, string) e fragil a variacao; por comportamento (o que o processo faz: conecta, modifica, persiste) e mais robusta. Entender as duas e base de EDR moderno e da analise que voce vai defender." },
      { topic: "Strings e IOCs.", text: "Extrair strings de um binario (comando, IP, dominio) revela indicadores (IOC) de ataque. IOCs alimentam regras de bloqueio e caça a ameacas. Em lab, aprenda a mapear o que procurar sem nunca hospedar amostra real." },
      { topic: "Detecção.", text: "Como o defensor pega malware: assinaturas de AV, comportamento de EDR, anomalia de rede. Para cada tecnica de ataque, apresente a deteccao correspondente. A banca de seguranca exige os dois lados documentados." },
      { topic: "Ética.", text: "Analise de malware e para defesa e pesquisa autorizada. Criar ou disseminar e crime (Lei 12.737 e afins). Sempre deixe explicito o proposito educacional e o isolamento. Etica nao e opcional no seu portifolio." }
    ],
    "red/s8": [
      { topic: "OPSEC básico.", text: "OPSEC (operacoes de seguranca) e proteger suas proprias informacoes e reduzir a superficie de ataque. Em lab, ensina a pensar como defensor: o que vaza, o que expoe. Na pratica ofensiva nao autorizada, e evasao ilegal — deixa claro o contexto." },
      { topic: "Evasão de logs.", text: "Evasao de logs (limpar historico, timestomping) remove rastros. EM LAB, serve para entender como o atacante some e como o defensor deve capturar telemetria. Fora do autorizado, e destruicao de evidencia. Estude para detectar, documente para defender." },
      { topic: "Living-off-the-land.", text: "LoLBin (living off the land) abusa de ferramentas legítimas do sistema (powershell, certutil) para agir sem trazer malware. Entender isso e chave para deteccao moderna (EDR olha comportamento, nao so arquivo). Defesa aprende com ataque." },
      { topic: "Timestomping (teoria).", text: "Timestomping altera timestamps de arquivos para confundir a linha do tempo forense. EM TEORIA, voce entende o vetor e por que logs centralizados e imutaveis (SIEM) sao a defesa. Material de estudo de forense, nao de pratica criminosa." },
      { topic: "Detecção.", text: "O defensor detecta evasao por inconsistencia de logs, gaps temporais, processos anomos. Sempre feche o topico com 'como o azul pega isso' — e o que eleva seu relatorio de 'achei' para 'recomendo defesa'." },
      { topic: "Legal.", text: "Toda tecnica de evasao carrega implicacao legal. Em seu portifolio, deixe explicito que e estudo em lab isolado e autorizado. A banca de seguranca elimina candidatos que confundem laboratorio com autorizacao real." }
    ],
    "red/s9": [
      { topic: "Resumo executivo.", text: "O resumo executivo e a primeira pagina: para quem decide, qual o risco e o que fazer. Sem jargao. Se o cliente so le esse trecho, deve entender o impacto. A banca avalia sua comunicacao com nao-tecnicos." },
      { topic: "Metodologia.", text: "Descreva como voce testou: escopo, ferramentas, passos. Reprodutibilidade e a diferenca entre 'achei algo' e 'relatorio serio'. A banca quer seguir seus passos e chegar no mesmo resultado." },
      { topic: "Achados + CVSS.", text: "Cada achado tem severidade (CVSS), descricao, impacto e prova. Liste ordenado por risco. Isso transforma teste em gestao de vulnerabilidades. Sem CVSS, o relatorio e opiniao; com ele, e mensuracao." },
      { topic: "Evidências.", text: "Provas (screenshots, payloads, hashes) tornam o achado inegavel e reproduzivel. Sempre inclua como chegou la. Evidencia e o que sustenta sua palavra perante a banca e o cliente." },
      { topic: "Gráficos.", text: "Graficos de risco (barras por severidade, mapa de ataque) comunicam mais que texto. Use matplotlib ou drawio. Visualizacao clara e sinal de maturidade analitica." },
      { topic: "Pitch.", text: "O pitch de 5 min resume o relatorio para decisores. Pratique gravado: problema, impacto, recomendacao. A banca avalia sua capacidade de sintetizar e influenciar." }
    ],
    "red/s10": [
      { topic: "O que é purple.", text: "Purple team e a colaboracao entre vermelho (ataca) e azul (defende) para melhorar os dois. Nao e uma terceira equipe, e o loop de feedback. O objetivo e que o azul detecte o que o vermelho faz." },
      { topic: "Mapear MITRE.", text: "MITRE ATT&CK e a matriz de tecnicas de adversario (initial access, execution, etc). Mapear seus testes no ATT&CK mostra cobertura e lacunas. A banca espera que voce fale a linguagem do framework." },
      { topic: "Teste + detecção.", text: "Para cada ataque simulado, o azul deve ter detectado? Se nao, ajuste regra. O purple loop mede 'o que o vermelho faz o azul pega'. Esse fechamento e o valor real, nao so quebrar o sistema." },
      { topic: "Feedback loop.", text: "O loop e: vermelho ataca -> azul detecta/falha -> ajusta controle -> re-teste. Continuo, nao pontual. Documente o ciclo para mostrar maturidade de programa de seguranca, nao so teste avulso." },
      { topic: "Metricas.", text: "Meça MTTC (tempo de detectar) e MTTR (tempo de responder) e cobertura de controles. Metricas provam melhora ao longo do tempo. A banca quer ver evolucao quantificavel, nao so 'esta melhor'." },
      { topic: "Cultura.", text: "Purple teaming so funciona com cultura de colaboracao, nao culpa. O objetivo e fortalecer o sistema, nao apontar erro de pessoa. Comunique isso no relatorio: seguranca e trabalho de time." }
    ]
  };

  module.exports = { EXPLAIN: EXPLAIN };
})();
